# Example workflow for your source repository (e.g., kamilczerw/otter)
# Copy this to your source repo at: .github/workflows/update-ha-addon.yml

name: Update Home Assistant Addon

on:
  release:
    types: [published]

jobs:
  trigger-addon-update:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger HA Addon Version Update
        run: |
          # Extract addon name from repository name (e.g., "otter" from "kamilczerw/otter")
          ADDON_NAME="${GITHUB_REPOSITORY##*/}"

          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.HA_ADDONS_TRIGGER_TOKEN }}" \
            https://api.github.com/repos/kamilczerw/ha-addons/dispatches \
            -d "{
              \"event_type\": \"update-addon-version\",
              \"client_payload\": {
                \"addon_name\": \"${ADDON_NAME}\",
                \"source_repo\": \"${GITHUB_REPOSITORY}\"
              }
            }"

      - name: Check trigger status
        run: |
          if [ $? -eq 0 ]; then
            echo "✅ Successfully triggered HA addon update workflow"
          else
            echo "❌ Failed to trigger HA addon update workflow"
            exit 1
          fi
